### ISSUE TITLE
Release tasks for version 0.1

### ISSUE THREAD

**Issue by andreww** [murphyqm/pytesimal#22]
The last thing to do before making a version of the code available is to make a release and generate a DOI. Instructions for doing this are at https://guides.github.com/activities/citable-code/. The v1.0.0 version number probably makes sense. You'll need to make the repository public first.

**Comment by murphyqm** [comment]
[![DOI](https://zenodo.org/badge/292811671.svg)](https://zenodo.org/badge/latestdoi/292811671)
