### ISSUE TITLE
Contracts warning

### ISSUE THREAD

**Issue by andreww** [murphyqm/pytesimal#34]
Just a quick note so we don't forget that the contracts module is generating warnings from the test suite. For example:

```
required_scripts/test_highlevel.py::test_def_const
  /anaconda3/envs/pytesimal/lib/python3.8/site-packages/contracts/library/miscellaneous_aliases.py:19: DeprecationWarning: Using or importing the ABCs from 'collections' instead of from 'collections.abc' is deprecated since Python 3.3, and in 3.9 it will stop working
    m_new_contract('Container', ist(collections.Container))
```

I think the plan is to remove remove the contracts decorators and replace with suitable unit tests at some point.

**Comment by murphyqm** [comment]
Looks like PyContracts is no longer being maintained - this has been raised as an issue on the software repository.

Some potential alternatives for type checking:

- https://github.com/Parquery/icontract
- https://pypi.org/project/pytreaty/#description (a fork of PyContracts when issues weren't responded to)

**Comment by murphyqm** [comment]
Removed/commented out contracts decorators, replaced with tests - type specification too restrictive for some functions which can take scalars or arrays as arguments
